# 项目主页: https://github.com/Sonarr/Sonarr
# https://docs.linuxserver.io/images/docker-sonarr/#parameters

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./media:/media
    ports:
      - 8989:8989
    restart: always