# 项目主页: https://evine.win/p/docker-install-qbittorrent/#docker-compose
# docker hub 更新页: https://hub.docker.com/r/nevinee/qbittorrent/tags

services:
  qbittorrent-nevinee:
    image: nevinee/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    tty: true
    volumes:
      - ./data:/data
    # working_dir: /data # 可选
    environment:
      - WEBUI_PORT=8080
      - BT_PORT=34567
      - PUID=1000
      - PGID=1000
      - UMASK_SET=000
      - TRACKER_ERROR_COUNT_MIN=300
      - ENABLE_AUTO_CATEGORY=false
      - EXTRA_PACKAGES=mediainfo
      - CRON_HEALTH_CHECK=12 * * * *
      #- MONITOR_IP=192.168.1.5 192.168.1.9 192.168.1.20
      - QB_USERNAME=${QB_USERNAME}
      - QB_PASSWORD=${QB_PASSWORD}
      - DL_FINISH_NOTIFY=true
      - TZ=Asia/Shanghai
      # - TG_USER_ID=${TG_USER_ID} # 可选
      # - TG_BOT_TOKEN=${TG_BOT_TOKEN} # 可选
    ports:
      - 8080:8080       # 冒号左右一致，必须同WEBUI_PORT一样，本文件中的3个8080要改一起改
      - 34567:34567      # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改
      - 34567:34567/udp  # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改
      #- 8787:8787       # 如使用的是nevinee/qbittorrent:iyuu标签，请解除本行注释
    #security_opt:       # armv7设备请解除本行和下一行的注释
      #- seccomp=unconfined