# 项目主页: https://hub.docker.com/r/linuxserver/homeassistant

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
      # - /etc/localtime:/etc/localtime:ro 不同版本主机可能路径不一样
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: always