# 项目主页: https://github.com/linuxserver/docker-firefox

services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
      - CUSTOM_USER=linuxdo
      - PASSWORD=${PASSWORD:-password}
    volumes:
      - ./config:/config
    ports:
      - 3000:3000 # http
      - 3001:3001 # https
    shm_size: "1gb"
    restart: unless-stopped