---
# 项目主页: https://github.com/Lissy93/dashy
# docker hub 更新页: https://hub.docker.com/r/lissy93/dashy/tags

# Welcome to Dashy! To get started, run `docker compose up -d`
# You can configure your container here, by modifying this file
# version: "3.8"

services:
  dashy:
    container_name: dashy

    # Pull latest image from DockerHub
    image: lissy93/dashy

    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .

    # You can also use an image with a different tag, or pull from a different registry, e.g:
    # image: ghcr.io/lissy93/dashy or image: lissy93/dashy:3.0.0

    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - ./config.yml:/app/user-data/conf.yml
      - ./icons:/app/user-data/item-icons/

    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 8080:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - PUID=1000
      - PGID=1000
    # Specify restart policy
    restart: always

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s